### ISSUE TITLE
Let's make friends!

### ISSUE THREAD

**Issue by stanislaw** [sagivo/algorithms#33]
Hello, @sagivo.

I am one of the contributors to similar repository: [EKAlgorithms](https://github.com/EvgenyKarkan/EKAlgorithms) - Objective-C implementations of common algorithms. 

Few days ago I discovered this your repository and decided to add a [link to it](https://github.com/EvgenyKarkan/EKAlgorithms/blob/master/README.md#similar-repositories) on EKAlgorithms main page. I suggest you doing the same. Let's make friends!

Thanks,

Stanislaw

**Comment by EvgenyKarkan** [comment]
:+1:

**Comment by sagivo** [comment]
thanks but cross-promotions is not my thing. i really like what you did but it's less relevant for ruby developers.

**Comment by stanislaw** [comment]
Ok, I got it. It was clear from your silence on this one while you was working actively on other tickets. 

The whole thing is not about "cross-promotions" since both repos are already promoted enough but about sharing of relevant code base - if I am a developer who is looking for some algorithms - for me it would be good to know that there are additional sources where I can find what I am looking for. I think many developers think about code sharing this way and also pretty lot of projects here at Github contain sections like: "Similar projects", "Alternatives" etc.

I hope this makes sense :)

Thanks for feedback.
